<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Rôles et permissions : `role_acces`, `user_role_acces`, `user.super_admin`.
 *
 * NON DESTRUCTIF. Deux tables créées, une colonne ajoutée à une table déjà remplie — d'où
 * `super_admin` en NOT NULL **avec DEFAULT** (§13). La colonne `user.roles` (le tableau de
 * rôles de Symfony) n'est **pas** touchée : elle reste la porte d'entrée `ROLE_USER`.
 *
 * ⚠️ **Personne ne doit perdre d'accès au déploiement.** Jusqu'ici, tout compte connecté
 * pouvait tout faire ; la migration attribue donc « Responsable foot » à **tous** les comptes
 * existants. Un déploiement de sécurité qui commence par bloquer les gens en place se fait
 * annuler dans l'heure, et c'est le blocage qu'on retient, pas la sécurité.
 *
 * Le super-admin était jusqu'ici *déduit* de l'email de redirection du mode bêta
 * (`DIAG_EMAIL`) : le backfill reprend exactement ce compte-là, pour que l'état après
 * migration soit celui d'avant. La lecture de l'environnement est faite **ici et une seule
 * fois** — après cette migration, le statut est un fait porté par le compte.
 *
 * Garde-fou : si des comptes existent et qu'aucun n'a été désigné super-admin, la migration
 * **échoue**. Une base peuplée sans super-admin est une base dont plus personne ne peut
 * rouvrir les droits. Une base vide (installation neuve, base de test) passe sans bruit :
 * il n'y a rien à protéger, et `app:seed-referential` fera le reste.
 *
 * Les permissions des deux rôles sont un **instantané figé à cette date**, pas une lecture
 * de `RolesSysteme` : une migration est un contrat entre deux états de la base. Le
 * référentiel du code peut évoluer ensuite sans réécrire l'histoire.
 */
final class Version20260829200000 extends AbstractMigration
{
    private const RESPONSABLE_FOOT = 'Responsable foot';

    /**
     * Instantané des permissions au 29/08/2026.
     *
     * Deux rôles seulement : les deux fonctions qui existent dans tous les clubs. En livrer
     * davantage reviendrait à deviner l'organigramme du club, et un rôle livré inutilisé
     * encombre l'écran sans pouvoir être supprimé.
     *
     * @var array<string, list<string>>
     */
    private const ROLES = [
        self::RESPONSABLE_FOOT => [
            'effectif.lire', 'effectif.gerer', 'effectif.importer', 'effectif.supprimer',
            'paiement.lire', 'paiement.encaisser', 'paiement.attester', 'licence.valider_fff',
            'dotation.lire', 'dotation.gerer', 'dotation.configurer',
            'stock.lire', 'stock.gerer', 'stock.configurer',
            'commande.lire', 'commande.gerer',
            'cle.lire', 'cle.gerer',
            'boutique.lire', 'boutique.gerer',
            'planning.lire', 'planning.gerer',
            'saison.lire', 'saison.configurer',
            'club.configurer',
        ],
        'Trésorerie' => [
            'effectif.lire',
            'paiement.lire', 'paiement.encaisser', 'paiement.attester', 'licence.valider_fff',
            'saison.lire',
        ],
    ];

    public function getDescription(): string
    {
        return 'Rôles et permissions : table role_acces, liaison user_role_acces, drapeau user.super_admin';
    }

    public function up(Schema $schema): void
    {
        // — Expand —
        $this->addSql(<<<'SQL'
            CREATE TABLE role_acces (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                nom VARCHAR(60) NOT NULL,
                permissions JSON NOT NULL,
                systeme BOOLEAN DEFAULT false NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql('CREATE UNIQUE INDEX UNIQ_2728D33F6C6E55B5 ON role_acces (nom)');

        $this->addSql(<<<'SQL'
            CREATE TABLE user_role_acces (
                user_id INT NOT NULL,
                role_acces_id INT NOT NULL,
                PRIMARY KEY (user_id, role_acces_id)
            )
            SQL);

        $this->addSql('CREATE INDEX IDX_804F15D3A76ED395 ON user_role_acces (user_id)');
        $this->addSql('CREATE INDEX IDX_804F15D3D6D6599C ON user_role_acces (role_acces_id)');

        // CASCADE des deux côtés : la liaison n'a aucun sens sans l'un ou l'autre.
        $this->addSql(<<<'SQL'
            ALTER TABLE user_role_acces
                ADD CONSTRAINT FK_USER_ROLE_ACCES_USER FOREIGN KEY (user_id)
                REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_role_acces
                ADD CONSTRAINT FK_USER_ROLE_ACCES_ROLE FOREIGN KEY (role_acces_id)
                REFERENCES role_acces (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);

        $this->addSql('ALTER TABLE "user" ADD super_admin BOOLEAN DEFAULT false NOT NULL');

        // — Backfill —
        foreach (self::ROLES as $nom => $permissions) {
            $this->addSql(
                'INSERT INTO role_acces (nom, permissions, systeme, created_at) VALUES (:nom, :permissions, true, NOW())',
                [
                    'nom' => $nom,
                    'permissions' => json_encode($permissions, JSON_THROW_ON_ERROR),
                ],
            );
        }

        $this->addSql(
            <<<'SQL'
                INSERT INTO user_role_acces (user_id, role_acces_id)
                SELECT u.id, r.id FROM "user" u CROSS JOIN role_acces r WHERE r.nom = :nom
                SQL,
            ['nom' => self::RESPONSABLE_FOOT],
        );

        $emailDiag = $this->emailDiag();

        if ($emailDiag !== '') {
            $this->addSql('UPDATE "user" SET super_admin = true WHERE email = :email', ['email' => $emailDiag]);
        }
    }

    /**
     * Le garde-fou tourne après le SQL : une base peuplée qui ressort sans super-admin est
     * une base que plus personne ne peut administrer. L'exception annule la transaction.
     */
    public function postUp(Schema $schema): void
    {
        // `--dry-run` appelle quand même postUp sans avoir joué le DDL : la colonne n'existe
        // pas encore, et il n'y a rien à vérifier puisque rien n'a été écrit.
        if (!isset($this->connection->createSchemaManager()->listTableColumns('user')['super_admin'])) {
            return;
        }

        $comptes = (int) $this->connection->fetchOne('SELECT COUNT(*) FROM "user"');

        if ($comptes === 0) {
            return;
        }

        $superAdmins = (int) $this->connection->fetchOne('SELECT COUNT(*) FROM "user" WHERE super_admin = true');

        if ($superAdmins === 0) {
            throw new \RuntimeException(
                'Aucun compte n\'a été désigné super-admin : vérifiez que DIAG_EMAIL correspond bien '
                . 'à l\'email d\'un compte existant, puis rejouez la migration. Sans super-admin, '
                . 'plus personne ne pourra rouvrir les droits après une fausse manœuvre.',
            );
        }
    }

    public function down(Schema $schema): void
    {
        // DESTRUCTIF : les rôles composés par le club et leurs affectations sont perdus.
        $this->addSql('ALTER TABLE user_role_acces DROP CONSTRAINT FK_USER_ROLE_ACCES_USER');
        $this->addSql('ALTER TABLE user_role_acces DROP CONSTRAINT FK_USER_ROLE_ACCES_ROLE');
        $this->addSql('DROP TABLE user_role_acces');
        $this->addSql('DROP TABLE role_acces');
        $this->addSql('ALTER TABLE "user" DROP super_admin');
    }

    private function emailDiag(): string
    {
        $valeur = $_ENV['DIAG_EMAIL'] ?? $_SERVER['DIAG_EMAIL'] ?? getenv('DIAG_EMAIL');

        return is_string($valeur) ? trim($valeur, " \t\n\r\0\x0B'\"") : '';
    }
}
