<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Attestations de paiement de licence : le document remis à qui a réglé, pour être
 * présenté à un employeur ou à un comité d'entreprise.
 *
 * NON DESTRUCTIF. Deux tables nouvelles, et des colonnes **toutes nullables** sur
 * `club_settings` — une table à ligne unique déjà remplie, où un NOT NULL sans défaut
 * échouerait. Aucune colonne existante n'est touchée.
 *
 * Le backfill ne renseigne que ce qui est certain : la raison sociale, l'adresse et le
 * signataire actuels, jusqu'ici écrits en dur dans les templates. Le SIRET est laissé
 * vide **délibérément** — l'exemplaire papier dont il est repris est un scan dont les
 * derniers chiffres sont illisibles, et un SIRET faux sur une attestation la disqualifie.
 * L'écran /admin/club/identite le signale à l'admin, qui le saisira.
 */
final class Version20260828120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les attestations de paiement et l\'identité de l\'association';
    }

    public function up(Schema $schema): void
    {
        /* ── Identité de l'association et signataire de ses attestations ── */
        $this->addSql('ALTER TABLE club_settings ADD association_nom VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD association_adresse VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD association_code_postal VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD association_ville VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD association_siret VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD association_email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD signataire_civilite VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD signataire_nom VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD signataire_qualite VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD signature_cachet_fichier VARCHAR(255) DEFAULT NULL');

        // Reprise de ce que les templates disaient déjà. Conditionné à la colonne vide :
        // rejouée après une saisie admin, la migration n'écraserait rien.
        $this->addSql(<<<'SQL'
            UPDATE club_settings SET
                association_nom         = COALESCE(association_nom, 'Foyer de Soudron'),
                association_adresse     = COALESCE(association_adresse, '1 Rue de l''Église'),
                association_code_postal = COALESCE(association_code_postal, '51320'),
                association_ville       = COALESCE(association_ville, 'Soudron'),
                association_email       = COALESCE(association_email, 'foyerdesoudron@gmail.com'),
                signataire_civilite     = COALESCE(signataire_civilite, 'mme'),
                signataire_nom          = COALESCE(signataire_nom, 'Claudine Moreaux'),
                signataire_qualite      = COALESCE(signataire_qualite, 'trésorière')
        SQL);

        /* ── L'attestation elle-même ── */
        $this->addSql(<<<'SQL'
            CREATE TABLE attestation_paiement (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                licencie_uuid UUID NOT NULL,
                season_id INT NOT NULL,
                licencie_nom VARCHAR(100) NOT NULL,
                licencie_prenom VARCHAR(100) NOT NULL,
                destinataire_civilite VARCHAR(10) NOT NULL,
                destinataire_nom VARCHAR(100) NOT NULL,
                destinataire_prenom VARCHAR(100) NOT NULL,
                lien_parente VARCHAR(20) NOT NULL,
                montant NUMERIC(8, 2) NOT NULL,
                montant_en_lettres VARCHAR(255) NOT NULL,
                date_paiement DATE NOT NULL,
                modes JSON NOT NULL,
                signataire_civilite VARCHAR(10) NOT NULL,
                signataire_nom VARCHAR(100) NOT NULL,
                signataire_qualite VARCHAR(100) NOT NULL,
                generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                generated_by_id INT DEFAULT NULL,
                drive_path VARCHAR(500) DEFAULT NULL,
                envoyee_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                envoyee_a VARCHAR(180) DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4066EFD3D17F50A6 ON attestation_paiement (uuid)');
        $this->addSql('CREATE INDEX idx_attestation_paiement_licencie ON attestation_paiement (licencie_uuid)');
        $this->addSql('CREATE INDEX IDX_4066EFD34EC001D1 ON attestation_paiement (season_id)');
        $this->addSql('CREATE INDEX IDX_4066EFD31BDD81B ON attestation_paiement (generated_by_id)');

        // Pas de ON DELETE sur le licencié : SuppressionFicheService refuse déjà de
        // supprimer une fiche dès qu'un paiement existe — donc dès qu'une attestation
        // a pu être émise. La contrainte est là pour que ce refus reste vrai en base.
        $this->addSql('ALTER TABLE attestation_paiement ADD CONSTRAINT FK_attestation_paiement_licencie FOREIGN KEY (licencie_uuid) REFERENCES licencie (uuid) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_paiement ADD CONSTRAINT FK_attestation_paiement_season FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_paiement ADD CONSTRAINT FK_attestation_paiement_user FOREIGN KEY (generated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        /* ── Les paiements attestés ──
           Simple trace de rapprochement : la vérité du document est dans les colonnes
           figées ci-dessus. D'où le CASCADE — un paiement supprimé plus tard retire la
           ligne de jointure sans jamais altérer ce que l'attestation affirme. */
        $this->addSql(<<<'SQL'
            CREATE TABLE attestation_paiement_transaction (
                attestation_id INT NOT NULL,
                transaction_id INT NOT NULL,
                PRIMARY KEY(attestation_id, transaction_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B10E70627EDC5B38 ON attestation_paiement_transaction (attestation_id)');
        $this->addSql('CREATE INDEX IDX_B10E70622FC0CB0F ON attestation_paiement_transaction (transaction_id)');
        $this->addSql('ALTER TABLE attestation_paiement_transaction ADD CONSTRAINT FK_apt_attestation FOREIGN KEY (attestation_id) REFERENCES attestation_paiement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_paiement_transaction ADD CONSTRAINT FK_apt_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // DESTRUCTIF : toutes les attestations émises disparaissent, ainsi que l'identité
        // de l'association et son signataire. Les PDF déjà archivés sur Drive survivent,
        // mais plus rien dans CoSync ne dit qu'ils existent ni à qui ils ont été remis.
        $this->addSql('DROP TABLE attestation_paiement_transaction');
        $this->addSql('DROP TABLE attestation_paiement');

        $this->addSql('ALTER TABLE club_settings DROP association_nom');
        $this->addSql('ALTER TABLE club_settings DROP association_adresse');
        $this->addSql('ALTER TABLE club_settings DROP association_code_postal');
        $this->addSql('ALTER TABLE club_settings DROP association_ville');
        $this->addSql('ALTER TABLE club_settings DROP association_siret');
        $this->addSql('ALTER TABLE club_settings DROP association_email');
        $this->addSql('ALTER TABLE club_settings DROP signataire_civilite');
        $this->addSql('ALTER TABLE club_settings DROP signataire_nom');
        $this->addSql('ALTER TABLE club_settings DROP signataire_qualite');
        $this->addSql('ALTER TABLE club_settings DROP signature_cachet_fichier');
    }
}
