<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Garde la trace des corrections apportées à un mouvement de stock saisi à la main.
 *
 * Jusqu'ici, rattraper une erreur de frappe demandait de supprimer la ligne pour la
 * ressaisir : deux gestes, et plus aucune trace de ce qui avait été écrit d'abord. Le
 * mouvement porte désormais la valeur juste, et cette table — append-only — dit ce qu'il
 * valait avant, quand, par qui, et sur quelle justification.
 *
 * NON DESTRUCTIF — une table neuve, vide à la création. Aucune colonne existante n'est
 * touchée : les mouvements déjà enregistrés restent tels quels, simplement sans correction.
 */
final class Version20260815180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée stock_movement_correction (historique des corrections de mouvements)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stock_movement_correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite_avant INT NOT NULL, quantite_apres INT NOT NULL, taille_avant VARCHAR(20) DEFAULT NULL, taille_apres VARCHAR(20) DEFAULT NULL, motif TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, movement_id INT NOT NULL, corrected_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD7EF0C3229E70A7 ON stock_movement_correction (movement_id)');
        $this->addSql('CREATE INDEX IDX_DD7EF0C38CF37DC4 ON stock_movement_correction (corrected_by_id)');
        $this->addSql('ALTER TABLE stock_movement_correction ADD CONSTRAINT FK_DD7EF0C3229E70A7 FOREIGN KEY (movement_id) REFERENCES stock_movement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_movement_correction ADD CONSTRAINT FK_DD7EF0C38CF37DC4 FOREIGN KEY (corrected_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // PERTE DE DONNÉES : l'historique des corrections. Les mouvements, eux, restent.
        $this->addSql('DROP TABLE stock_movement_correction');
    }
}
