<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608123829 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(10) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE stock_item ADD alert_seuil INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_item ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_item ADD CONSTRAINT FK_6017DDA12469DE2 FOREIGN KEY (category_id) REFERENCES stock_category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6017DDA12469DE2 ON stock_item (category_id)');
        $this->addSql('ALTER TABLE stock_movement ADD source VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE stock_movement ADD sumup_transaction_id VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_movement ALTER created_by_id DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE stock_category');
        $this->addSql('ALTER TABLE stock_item DROP CONSTRAINT FK_6017DDA12469DE2');
        $this->addSql('DROP INDEX IDX_6017DDA12469DE2');
        $this->addSql('ALTER TABLE stock_item DROP alert_seuil');
        $this->addSql('ALTER TABLE stock_item DROP category_id');
        $this->addSql('ALTER TABLE stock_movement DROP source');
        $this->addSql('ALTER TABLE stock_movement DROP sumup_transaction_id');
        $this->addSql('ALTER TABLE stock_movement ALTER created_by_id SET NOT NULL');
    }
}
