<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Journal des mails envoyés par le club.
 *
 * NON DESTRUCTIF. Une table nouvelle, aucune colonne existante touchée. `link_sent_at` et
 * `boutique_annoncee_at` restent en place : ce sont elles qui font foi pour les écrans
 * d'envoi groupé (« qui n'a jamais reçu son lien ? »), le journal ne les remplace pas.
 *
 * Le backfill n'est pas une commodité, il est **obligatoire** : l'historique des fiches
 * lit désormais le journal au lieu de `link_sent_at`, et sans reprise chaque licencié
 * déjà contacté perdrait sa ligne « lien envoyé ». On ne reprend que des faits datés et
 * certains — le premier envoi de chaque lien, l'annonce de la boutique. Les renvois
 * passés, eux, ne sont pas reconstructibles : la colonne écrasée n'en gardait rien.
 *
 * `destinataire_email` est repris de l'adresse **actuelle** de la fiche, faute de mieux :
 * l'adresse d'époque n'est nulle part. Vide quand la fiche n'en porte plus aucune — cas
 * marginal, et la ligne d'historique vaut mieux que son absence.
 */
final class Version20260829090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le journal des mails envoyés (EnvoiMail) et reprend les envois déjà datés';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE envoi_mail (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                type VARCHAR(40) NOT NULL,
                origine VARCHAR(20) NOT NULL,
                destinataire_email VARCHAR(180) NOT NULL,
                sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                licencie_uuid UUID DEFAULT NULL,
                dirigeant_uuid UUID DEFAULT NULL,
                detenteur_id INT DEFAULT NULL,
                declenche_par_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_B2FE2CB31694F1A2 ON envoi_mail (licencie_uuid)');
        $this->addSql('CREATE INDEX IDX_B2FE2CB31688CA9D ON envoi_mail (dirigeant_uuid)');
        $this->addSql('CREATE INDEX IDX_B2FE2CB3742F89B9 ON envoi_mail (detenteur_id)');
        $this->addSql('CREATE INDEX IDX_B2FE2CB3C16F920B ON envoi_mail (declenche_par_id)');

        // Index composés : l'historique d'une fiche et le « dernier contact » des listes
        // lisent tous par personne puis par date.
        $this->addSql('CREATE INDEX idx_envoi_mail_licencie ON envoi_mail (licencie_uuid, sent_at)');
        $this->addSql('CREATE INDEX idx_envoi_mail_dirigeant ON envoi_mail (dirigeant_uuid, sent_at)');
        $this->addSql('CREATE INDEX idx_envoi_mail_detenteur ON envoi_mail (detenteur_id, sent_at)');

        // CASCADE sur les trois rattachements : SuppressionFicheService refuse désormais de
        // supprimer une fiche dès qu'un mail lui est parti, la cascade ne se déclenche donc
        // pas en pratique. Elle garantit qu'un ménage fait en base ne laisse pas d'orphelin.
        $this->addSql('ALTER TABLE envoi_mail ADD CONSTRAINT FK_B2FE2CB31694F1A2 FOREIGN KEY (licencie_uuid) REFERENCES licencie (uuid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE envoi_mail ADD CONSTRAINT FK_B2FE2CB31688CA9D FOREIGN KEY (dirigeant_uuid) REFERENCES dirigeant (uuid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE envoi_mail ADD CONSTRAINT FK_B2FE2CB3742F89B9 FOREIGN KEY (detenteur_id) REFERENCES detenteur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        // SET NULL : un compte admin supprimé ne doit pas emporter la trace du mail qu'il a
        // déclenché. L'historique retombe alors sur l'origine (« Admin »).
        $this->addSql('ALTER TABLE envoi_mail ADD CONSTRAINT FK_B2FE2CB3C16F920B FOREIGN KEY (declenche_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        /* ── Reprise des envois déjà datés ──
           Origine « admin » : ces trois envois sont, tous les trois, des décisions prises
           sur un écran. Aucun ne part de lui-même. L'auteur, lui, n'est pas connu :
           declenche_par reste nul et l'historique affichera « Admin ». */
        $this->addSql(<<<'SQL'
            INSERT INTO envoi_mail (type, origine, destinataire_email, sent_at, licencie_uuid)
            SELECT 'inscription_link', 'admin', COALESCE(email, ''), link_sent_at, uuid
            FROM licencie WHERE link_sent_at IS NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO envoi_mail (type, origine, destinataire_email, sent_at, licencie_uuid)
            SELECT 'boutique', 'admin', COALESCE(email, ''), boutique_annoncee_at, uuid
            FROM licencie WHERE boutique_annoncee_at IS NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO envoi_mail (type, origine, destinataire_email, sent_at, dirigeant_uuid)
            SELECT 'dirigeant_link', 'admin', COALESCE(email, ''), link_sent_at, uuid
            FROM dirigeant WHERE link_sent_at IS NOT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // DESTRUCTIF : tout l'historique des mails envoyés disparaît. Les fiches
        // retrouvent leur ligne « lien envoyé » (link_sent_at n'a pas bougé), mais les
        // relances et les envois qui ne passent par aucun lien sont perdus.
        $this->addSql('DROP TABLE envoi_mail');
    }
}
