<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Sort les coordonnées bancaires de la saison pour en faire un réglage du club.
 *
 * Le RIB ne change pas d'une saison à l'autre : le porter sur `season` obligeait à le
 * re-saisir (ou à le recopier) à chaque rentrée, et le faisait apparaître dans l'écran de
 * configuration de la saison alors qu'il appartient à l'association.
 *
 * NON DESTRUCTIF — les colonnes season.iban / bic / titulaire_compte sont conservées telles
 * quelles. Elles ne sont plus mappées ni lues par l'application, mais restent le filet de
 * sécurité tant que la bascule n'est pas validée en production. Leur suppression fera
 * l'objet d'une migration séparée, explicitement destructive.
 *
 * Reprise des données : la ligne unique de club_settings est remplie depuis la saison la plus
 * récente possédant un IBAN, au sens du libellé (« 2025-2026 »), dont l'ordre lexicographique
 * est chronologique — contrairement à created_at, qui ne reflète que l'ordre de saisie. Si
 * aucune saison n'a d'IBAN, la ligne est créée vide : le formulaire public masque alors
 * l'option « virement », comme avant.
 *
 * Plusieurs saisons peuvent porter des RIB différents. Après déploiement, vérifier la valeur
 * reprise sur l'écran « Coordonnées bancaires » — elle est modifiable sans redéploiement.
 */
final class Version20260809160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée club_settings (ligne unique) et y reprend le RIB porté par la saison';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE club_settings (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                iban VARCHAR(34) DEFAULT NULL,
                bic VARCHAR(11) DEFAULT NULL,
                titulaire_compte VARCHAR(100) DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        // Reprise depuis la saison la plus récente qui a un IBAN renseigné.
        $this->addSql(<<<'SQL'
            INSERT INTO club_settings (iban, bic, titulaire_compte)
            SELECT iban, bic, titulaire_compte
            FROM season
            WHERE iban IS NOT NULL AND iban <> ''
            ORDER BY label DESC
            LIMIT 1
        SQL);

        // Aucune saison n'avait de RIB : la ligne unique doit exister malgré tout.
        $this->addSql(<<<'SQL'
            INSERT INTO club_settings (iban, bic, titulaire_compte)
            SELECT NULL, NULL, NULL
            WHERE NOT EXISTS (SELECT 1 FROM club_settings)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // Sans risque : les valeurs d'origine n'ont jamais quitté la table season.
        $this->addSql('DROP TABLE club_settings');
    }
}
