<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Le rôle d'un dirigeant devient un enum applicatif (App\Enum\DirigeantRole) au lieu
 * d'une table de référentiel : trois rôles fermés, plus aucun rôle créable depuis l'UI
 * ni depuis un import FootClubs.
 *
 * ⚠️ FICHIER RECONSTRUIT. L'original a été écrasé par erreur après avoir été appliqué en
 * développement. Le DDL ci-dessous a été rétabli à partir du schéma réel de la base ; le
 * backfill des anciens libellés, lui, a été redéduit des descriptions de l'enum :
 *   - bureau du foot (Président, Vice-Président, Secrétaire, Trésorier) → responsable_foot
 *   - Éducateur (coach principal d'une équipe)                          → responsable_equipe
 *   - tout le reste (Éducateur adjoint, Arbitre, Délégué, Accompagnateur, sans rôle)
 *                                                                       → dirigeant
 * À vérifier avant tout déploiement en production : c'est la seule partie qui n'a pas pu
 * être retrouvée à l'identique.
 */
final class Version20260807220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remplace la table dirigeant_role par un enum applicatif sur dirigeant.role.';
    }

    public function up(Schema $schema): void
    {
        // Expand : colonne nullable le temps du backfill (la table dirigeant est peuplée).
        $this->addSql("ALTER TABLE dirigeant ADD role VARCHAR(32) DEFAULT 'dirigeant'");

        // Backfill depuis le référentiel, avant sa suppression.
        $this->addSql(<<<'SQL'
            UPDATE dirigeant d
            SET role = CASE r.label
                WHEN 'Président'      THEN 'responsable_foot'
                WHEN 'Vice-Président' THEN 'responsable_foot'
                WHEN 'Secrétaire'     THEN 'responsable_foot'
                WHEN 'Trésorier'      THEN 'responsable_foot'
                WHEN 'Éducateur'      THEN 'responsable_equipe'
                ELSE 'dirigeant'
            END
            FROM dirigeant_role r
            WHERE r.id = d.role_id
        SQL);

        // Les dirigeants sans rôle défini rejoignent le rôle par défaut.
        $this->addSql("UPDATE dirigeant SET role = 'dirigeant' WHERE role IS NULL");

        // Contract : la colonne devient obligatoire une fois toutes les lignes remplies.
        $this->addSql('ALTER TABLE dirigeant ALTER COLUMN role SET NOT NULL');

        // DESTRUCTIF : le référentiel des rôles et son rattachement disparaissent.
        $this->addSql('ALTER TABLE dirigeant DROP CONSTRAINT IF EXISTS FK_dirigeant_role');
        $this->addSql('ALTER TABLE dirigeant DROP CONSTRAINT IF EXISTS FK_BEC71E71D60322AC');
        $this->addSql('DROP INDEX IF EXISTS IDX_BEC71E71D60322AC');
        $this->addSql('DROP INDEX IF EXISTS IDX_dirigeant_role_id');
        $this->addSql('ALTER TABLE dirigeant DROP COLUMN role_id');
        $this->addSql('DROP TABLE dirigeant_role');
    }

    /**
     * DESTRUCTIF et partiel : le référentiel est recréé avec ses rôles par défaut, mais
     * les trois valeurs d'enum ne permettent pas de retrouver le libellé d'origine de
     * chaque dirigeant. Tous repartent sans rôle.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE dirigeant_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(100) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_909E1051EA750E8 ON dirigeant_role (label)');
        $this->addSql("INSERT INTO dirigeant_role (label, sort_order) VALUES
            ('Président', 10),
            ('Vice-Président', 20),
            ('Secrétaire', 30),
            ('Trésorier', 40),
            ('Éducateur', 50),
            ('Éducateur adjoint', 60),
            ('Arbitre', 70),
            ('Délégué', 80),
            ('Accompagnateur', 90)
        ");

        $this->addSql('ALTER TABLE dirigeant ADD role_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE dirigeant ADD CONSTRAINT FK_BEC71E71D60322AC FOREIGN KEY (role_id) REFERENCES dirigeant_role (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_BEC71E71D60322AC ON dirigeant (role_id)');
        $this->addSql('ALTER TABLE dirigeant DROP COLUMN role');
    }
}
