<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Section « Club house » : registre des clés du local et attestation de remise signée.
 *
 * - cle_mouvement : table d'événements append-only (remise / restitution / perte).
 *   La détention courante est dérivée de l'historique, jamais stockée.
 * - dirigeant.attestation_cle_* : parcours de signature de l'attestation, avec son
 *   propre token, strictement indépendant de form_token_expires_at.
 * - season.attestation_cle_text : texte de l'attestation, éditable par saison.
 *
 * Les quatre ADD COLUMN sont nullables sans NOT NULL : PostgreSQL les ajoute en
 * métadonnée seule, aucun backfill n'est nécessaire sur les tables déjà remplies
 * (NULL = pas encore signé). cle_mouvement est créée vide, ses FK NOT NULL sont
 * donc posables d'emblée.
 */
final class Version20260801120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Registre des clés du club house (cle_mouvement) et attestation de remise signée (colonnes dirigeant + season).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cle_mouvement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, quantite INT NOT NULL, date_mouvement DATE NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dirigeant_id UUID NOT NULL, season_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_45D1DEB4E233AF25 ON cle_mouvement (dirigeant_id)');
        $this->addSql('CREATE INDEX IDX_45D1DEB44EC001D1 ON cle_mouvement (season_id)');
        $this->addSql('CREATE INDEX IDX_45D1DEB4B03A8386 ON cle_mouvement (created_by_id)');
        $this->addSql('ALTER TABLE cle_mouvement ADD CONSTRAINT FK_45D1DEB4E233AF25 FOREIGN KEY (dirigeant_id) REFERENCES dirigeant (uuid) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cle_mouvement ADD CONSTRAINT FK_45D1DEB44EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cle_mouvement ADD CONSTRAINT FK_45D1DEB4B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('ALTER TABLE dirigeant ADD attestation_cle_signe_path VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE dirigeant ADD attestation_cle_signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE dirigeant ADD attestation_cle_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        $this->addSql('ALTER TABLE season ADD attestation_cle_text TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE season DROP attestation_cle_text');

        $this->addSql('ALTER TABLE dirigeant DROP attestation_cle_token_expires_at');
        $this->addSql('ALTER TABLE dirigeant DROP attestation_cle_signed_at');
        $this->addSql('ALTER TABLE dirigeant DROP attestation_cle_signe_path');

        $this->addSql('ALTER TABLE cle_mouvement DROP CONSTRAINT FK_45D1DEB4E233AF25');
        $this->addSql('ALTER TABLE cle_mouvement DROP CONSTRAINT FK_45D1DEB44EC001D1');
        $this->addSql('ALTER TABLE cle_mouvement DROP CONSTRAINT FK_45D1DEB4B03A8386');
        $this->addSql('DROP TABLE cle_mouvement');
    }
}
