<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Donne au stock des grilles de tailles : la table de traduction entre ce qu'une personne
 * déclare (« 44 », « 12 ans ») et ce que le fournisseur étiquette (« 43-46 », « 128 »).
 *
 * NON DESTRUCTIF — trois tables neuves et une colonne nullable, rien n'est supprimé ni
 * réécrit :
 *  - `stock_item.grille_taille_id` est ajoutée nullable et **sans backfill** : `NULL` reproduit
 *    exactement le comportement actuel, où la taille déclarée est recopiée telle quelle. Les
 *    articles existants restent donc tels qu'ils sont jusqu'à ce qu'un admin leur attribue une
 *    grille ;
 *  - les deux côtés de la traduction pointent vers `taille`, jamais vers du texte libre : la
 *    cible est recopiée dans `stock_movement` et `dotation_besoin`, elle doit exister au
 *    référentiel. `TailleService` refuse déjà de supprimer une taille employée, et compte
 *    désormais les grilles parmi les emplois.
 *
 * Le diff auto-généré proposait au passage de supprimer `cle_mouvement.season_id`,
 * `cle_mouvement.dirigeant_id`, les colonnes d'attestation de `dirigeant` et les coordonnées
 * bancaires de `season` : ces colonnes sont dé-mappées mais conservées en base volontairement.
 * Elles ne figurent pas ici.
 */
final class Version20260815190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les grilles de tailles et les rattache aux articles de stock';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE grille_taille (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(20) NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE grille_taille_valeur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grille_id INT NOT NULL, cible_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DE200C9F985C2966 ON grille_taille_valeur (grille_id)');
        $this->addSql('CREATE INDEX IDX_DE200C9FA96E5E09 ON grille_taille_valeur (cible_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_grille_valeur_cible ON grille_taille_valeur (grille_id, cible_id)');
        $this->addSql('ALTER TABLE grille_taille_valeur ADD CONSTRAINT FK_DE200C9F985C2966 FOREIGN KEY (grille_id) REFERENCES grille_taille (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grille_taille_valeur ADD CONSTRAINT FK_DE200C9FA96E5E09 FOREIGN KEY (cible_id) REFERENCES taille (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE grille_taille_valeur_couverture (grille_taille_valeur_id INT NOT NULL, taille_id INT NOT NULL, PRIMARY KEY (grille_taille_valeur_id, taille_id))');
        $this->addSql('CREATE INDEX IDX_DEEB2EE97D555E7 ON grille_taille_valeur_couverture (grille_taille_valeur_id)');
        $this->addSql('CREATE INDEX IDX_DEEB2EE9FF25611A ON grille_taille_valeur_couverture (taille_id)');
        $this->addSql('ALTER TABLE grille_taille_valeur_couverture ADD CONSTRAINT FK_DEEB2EE97D555E7 FOREIGN KEY (grille_taille_valeur_id) REFERENCES grille_taille_valeur (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grille_taille_valeur_couverture ADD CONSTRAINT FK_DEEB2EE9FF25611A FOREIGN KEY (taille_id) REFERENCES taille (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE stock_item ADD grille_taille_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_item ADD CONSTRAINT FK_6017DDA6DF3F5D4 FOREIGN KEY (grille_taille_id) REFERENCES grille_taille (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_6017DDA6DF3F5D4 ON stock_item (grille_taille_id)');
    }

    public function down(Schema $schema): void
    {
        // PERTE DE DONNÉES : les grilles et le rattachement des articles. Les tailles du
        // référentiel, elles, survivent — elles vivent dans `taille`.
        $this->addSql('ALTER TABLE stock_item DROP CONSTRAINT FK_6017DDA6DF3F5D4');
        $this->addSql('DROP INDEX IDX_6017DDA6DF3F5D4');
        $this->addSql('ALTER TABLE stock_item DROP grille_taille_id');

        $this->addSql('DROP TABLE grille_taille_valeur_couverture');
        $this->addSql('DROP TABLE grille_taille_valeur');
        $this->addSql('DROP TABLE grille_taille');
    }
}
