<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Donne au stock des notes : une sur l'article, une par déclinaison de taille.
 *
 * NON DESTRUCTIF — une colonne nullable et une table neuve, rien n'est supprimé ni réécrit :
 *  - `stock_item.note` est ajoutée nullable, donc sans backfill : les articles existants
 *    restent sans note, ce qui est l'état voulu ;
 *  - `stock_taille_note` est vide à la création, et son article est en ON DELETE CASCADE —
 *    une note ne survit pas à l'article qu'elle commente.
 *
 * Le diff auto-généré proposait au passage de supprimer `cle_mouvement.season_id`,
 * `cle_mouvement.dirigeant_id`, les colonnes d'attestation de `dirigeant` et les
 * coordonnées bancaires de `season` : ces colonnes sont dé-mappées mais conservées en base
 * volontairement. Elles ne figurent pas ici.
 */
final class Version20260815160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute stock_item.note et la table stock_taille_note';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stock_item ADD note TEXT DEFAULT NULL');

        $this->addSql('CREATE TABLE stock_taille_note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taille VARCHAR(20) NOT NULL, note TEXT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3861E86126F525E ON stock_taille_note (item_id)');
        $this->addSql('CREATE INDEX IDX_F3861E86896DBBDE ON stock_taille_note (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_stock_taille_note ON stock_taille_note (item_id, taille)');
        $this->addSql('ALTER TABLE stock_taille_note ADD CONSTRAINT FK_F3861E86126F525E FOREIGN KEY (item_id) REFERENCES stock_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stock_taille_note ADD CONSTRAINT FK_F3861E86896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // PERTE DE DONNÉES : les notes saisies sur les articles et sur leurs tailles.
        $this->addSql('DROP TABLE stock_taille_note');
        $this->addSql('ALTER TABLE stock_item DROP note');
    }
}
