<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628151306 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Dotations : besoins par personne (statut à donner / donné)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dotation_besoin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, taille VARCHAR(20) DEFAULT NULL, statut VARCHAR(20) NOT NULL, groupe_choix VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, season_id INT NOT NULL, licencie_id UUID DEFAULT NULL, dirigeant_id UUID DEFAULT NULL, stock_item_id INT NOT NULL, mouvement_sortie_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC970C164EC001D1 ON dotation_besoin (season_id)');
        $this->addSql('CREATE INDEX IDX_CC970C16B56DCD74 ON dotation_besoin (licencie_id)');
        $this->addSql('CREATE INDEX IDX_CC970C16E233AF25 ON dotation_besoin (dirigeant_id)');
        $this->addSql('CREATE INDEX IDX_CC970C16BC942FD ON dotation_besoin (stock_item_id)');
        $this->addSql('CREATE INDEX IDX_CC970C163F48B45E ON dotation_besoin (mouvement_sortie_id)');
        $this->addSql('ALTER TABLE dotation_besoin ADD CONSTRAINT FK_CC970C164EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_besoin ADD CONSTRAINT FK_CC970C16B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (uuid) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_besoin ADD CONSTRAINT FK_CC970C16E233AF25 FOREIGN KEY (dirigeant_id) REFERENCES dirigeant (uuid) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_besoin ADD CONSTRAINT FK_CC970C16BC942FD FOREIGN KEY (stock_item_id) REFERENCES stock_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_besoin ADD CONSTRAINT FK_CC970C163F48B45E FOREIGN KEY (mouvement_sortie_id) REFERENCES stock_movement (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dotation_besoin DROP CONSTRAINT FK_CC970C164EC001D1');
        $this->addSql('ALTER TABLE dotation_besoin DROP CONSTRAINT FK_CC970C16B56DCD74');
        $this->addSql('ALTER TABLE dotation_besoin DROP CONSTRAINT FK_CC970C16E233AF25');
        $this->addSql('ALTER TABLE dotation_besoin DROP CONSTRAINT FK_CC970C16BC942FD');
        $this->addSql('ALTER TABLE dotation_besoin DROP CONSTRAINT FK_CC970C163F48B45E');
        $this->addSql('DROP TABLE dotation_besoin');
    }
}
