<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628134935 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Dotations : modèles, lignes et affectations';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dotation_affectation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, season_id INT NOT NULL, modele_id INT NOT NULL, category_id INT DEFAULT NULL, team_id INT DEFAULT NULL, licencie_id UUID DEFAULT NULL, dirigeant_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B05E06594EC001D1 ON dotation_affectation (season_id)');
        $this->addSql('CREATE INDEX IDX_B05E0659AC14B70A ON dotation_affectation (modele_id)');
        $this->addSql('CREATE INDEX IDX_B05E065912469DE2 ON dotation_affectation (category_id)');
        $this->addSql('CREATE INDEX IDX_B05E0659296CD8AE ON dotation_affectation (team_id)');
        $this->addSql('CREATE INDEX IDX_B05E0659B56DCD74 ON dotation_affectation (licencie_id)');
        $this->addSql('CREATE INDEX IDX_B05E0659E233AF25 ON dotation_affectation (dirigeant_id)');
        $this->addSql('CREATE TABLE dotation_modele (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, actif BOOLEAN NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D8D615F4EC001D1 ON dotation_modele (season_id)');
        $this->addSql('CREATE TABLE dotation_modele_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, obligatoire BOOLEAN NOT NULL, groupe_choix VARCHAR(50) DEFAULT NULL, modele_id INT NOT NULL, stock_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF1500C5AC14B70A ON dotation_modele_ligne (modele_id)');
        $this->addSql('CREATE INDEX IDX_FF1500C5BC942FD ON dotation_modele_ligne (stock_item_id)');
        $this->addSql('ALTER TABLE dotation_affectation ADD CONSTRAINT FK_B05E06594EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_affectation ADD CONSTRAINT FK_B05E0659AC14B70A FOREIGN KEY (modele_id) REFERENCES dotation_modele (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_affectation ADD CONSTRAINT FK_B05E065912469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_affectation ADD CONSTRAINT FK_B05E0659296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_affectation ADD CONSTRAINT FK_B05E0659B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (uuid) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_affectation ADD CONSTRAINT FK_B05E0659E233AF25 FOREIGN KEY (dirigeant_id) REFERENCES dirigeant (uuid) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_modele ADD CONSTRAINT FK_5D8D615F4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_modele_ligne ADD CONSTRAINT FK_FF1500C5AC14B70A FOREIGN KEY (modele_id) REFERENCES dotation_modele (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dotation_modele_ligne ADD CONSTRAINT FK_FF1500C5BC942FD FOREIGN KEY (stock_item_id) REFERENCES stock_item (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dotation_affectation DROP CONSTRAINT FK_B05E06594EC001D1');
        $this->addSql('ALTER TABLE dotation_affectation DROP CONSTRAINT FK_B05E0659AC14B70A');
        $this->addSql('ALTER TABLE dotation_affectation DROP CONSTRAINT FK_B05E065912469DE2');
        $this->addSql('ALTER TABLE dotation_affectation DROP CONSTRAINT FK_B05E0659296CD8AE');
        $this->addSql('ALTER TABLE dotation_affectation DROP CONSTRAINT FK_B05E0659B56DCD74');
        $this->addSql('ALTER TABLE dotation_affectation DROP CONSTRAINT FK_B05E0659E233AF25');
        $this->addSql('ALTER TABLE dotation_modele DROP CONSTRAINT FK_5D8D615F4EC001D1');
        $this->addSql('ALTER TABLE dotation_modele_ligne DROP CONSTRAINT FK_FF1500C5AC14B70A');
        $this->addSql('ALTER TABLE dotation_modele_ligne DROP CONSTRAINT FK_FF1500C5BC942FD');
        $this->addSql('DROP TABLE dotation_affectation');
        $this->addSql('DROP TABLE dotation_modele');
        $this->addSql('DROP TABLE dotation_modele_ligne');
    }
}
