<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Grille d'occupation des terrains : `espace_terrain` et `creneau_occupation`.
 *
 * NON DESTRUCTIF : deux tables neuves, aucune colonne touchée ailleurs.
 *
 * ⚠️ Le `doctrine:migrations:diff` qui a produit ce squelette proposait aussi de supprimer
 * des colonnes de `cle_mouvement`, `dirigeant` et `season` : c'est une **dérive de la base
 * de développement**, restée en arrière d'entités déjà nettoyées, et non un effet de cette
 * fonctionnalité. Ces `DROP` ont été retirés — les jouer sur la production ferait perdre des
 * données sans rapport avec la grille.
 *
 * Ce que la structure porte, et pourquoi :
 *
 * - `espace_terrain` n'a **pas** de `season_id` : un terrain ne change pas de nom au
 *   1ᵉʳ juillet, et c'est ce qui permet de reprendre la grille d'une saison sur l'autre.
 * - `heure_debut` / `heure_fin` sont des `VARCHAR(5)` et non des `TIME` : ce sont des
 *   libellés qu'on imprime, jamais des instants qu'on calcule (même raison que
 *   `match_domicile.heure` — un `TIME` ferait entrer un fuseau dans un document papier).
 * - `equipe_id` est **nullable, en `SET NULL`** : supprimer une équipe depuis l'écran des
 *   équipes ne doit ni échouer sur une contrainte, ni emporter des créneaux en silence. Le
 *   créneau reste, sans équipe, et la grille le signale.
 * - `espace_id` est `NOT NULL` sans `ON DELETE` : un terrain encore réservé ne se supprime
 *   pas, et `EspaceTerrainService` refuse avant d'en arriver à la contrainte.
 *
 * Aucun terrain n'est créé ici. Le complexe de Soudron — deux terrains d'entraînement et un
 * terrain d'honneur divisible en deux — est une **reprise de données du club**, pas un
 * référentiel qui vaudrait pour toute base : il est porté par la commande idempotente
 * `app:occupation:terrains-soudron`, qui ne se rejoue pas sur la base neuve de la CI.
 */
final class Version20260908212440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Grille d\'occupation des terrains : espace_terrain et creneau_occupation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE espace_terrain (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(80) NOT NULL, ordre INT NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_espace_terrain_nom ON espace_terrain (nom)');

        $this->addSql('CREATE TABLE creneau_occupation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour VARCHAR(10) NOT NULL, heure_debut VARCHAR(5) NOT NULL, heure_fin VARCHAR(5) NOT NULL, usage VARCHAR(15) NOT NULL, season_id INT NOT NULL, equipe_id INT DEFAULT NULL, espace_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_creneau_occupation_season ON creneau_occupation (season_id)');
        $this->addSql('CREATE INDEX IDX_5B4DA1726D861B89 ON creneau_occupation (equipe_id)');
        $this->addSql('CREATE INDEX IDX_5B4DA172B6885C6C ON creneau_occupation (espace_id)');

        $this->addSql('ALTER TABLE creneau_occupation ADD CONSTRAINT FK_5B4DA1724EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE creneau_occupation ADD CONSTRAINT FK_5B4DA1726D861B89 FOREIGN KEY (equipe_id) REFERENCES team (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE creneau_occupation ADD CONSTRAINT FK_5B4DA172B6885C6C FOREIGN KEY (espace_id) REFERENCES espace_terrain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /**
     * ⚠️ Retour arrière **destructeur** : la grille d'occupation et le référentiel des
     * terrains sont perdus. Il n'y a pas d'autre trace en base — seuls les PDF archivés sur
     * le Drive du club diraient encore ce qui avait été transmis à la mairie.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE creneau_occupation DROP CONSTRAINT FK_5B4DA1724EC001D1');
        $this->addSql('ALTER TABLE creneau_occupation DROP CONSTRAINT FK_5B4DA1726D861B89');
        $this->addSql('ALTER TABLE creneau_occupation DROP CONSTRAINT FK_5B4DA172B6885C6C');
        $this->addSql('DROP TABLE creneau_occupation');
        $this->addSql('DROP TABLE espace_terrain');
    }
}
