<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260516100518 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, label VARCHAR(50) NOT NULL, is_ecole_foot BOOLEAN NOT NULL, min_year INT NOT NULL, max_year INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C177153098 ON category (code)');
        $this->addSql('CREATE TABLE dossier_club (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taille_haut VARCHAR(20) DEFAULT NULL, taille_bas VARCHAR(20) DEFAULT NULL, pointure VARCHAR(10) DEFAULT NULL, autorisation_photo BOOLEAN DEFAULT NULL, autorisation_transport_dirigeants BOOLEAN DEFAULT NULL, autorisation_transport_parents BOOLEAN DEFAULT NULL, payment_intention VARCHAR(255) DEFAULT NULL, is_signed BOOLEAN NOT NULL, signature_path VARCHAR(500) DEFAULT NULL, signature_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, form_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) NOT NULL, licencie_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34D4F901B56DCD74 ON dossier_club (licencie_id)');
        $this->addSql('CREATE TABLE licencie (uuid UUID NOT NULL, num_licence VARCHAR(50) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, date_naissance DATE NOT NULL, email VARCHAR(180) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, form_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, team_id INT DEFAULT NULL, season_id INT NOT NULL, PRIMARY KEY (uuid))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B755612D8A9FCA1 ON licencie (num_licence)');
        $this->addSql('CREATE INDEX IDX_3B75561212469DE2 ON licencie (category_id)');
        $this->addSql('CREATE INDEX IDX_3B755612296CD8AE ON licencie (team_id)');
        $this->addSql('CREATE INDEX IDX_3B7556124EC001D1 ON licencie (season_id)');
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, base_costs JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stock_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, couleur VARCHAR(50) DEFAULT NULL, ref_catalogue VARCHAR(100) DEFAULT NULL, lien_achat VARCHAR(500) DEFAULT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6017DDA4EC001D1 ON stock_item (season_id)');
        $this->addSql('CREATE TABLE stock_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, type VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_id INT NOT NULL, licencie_id UUID DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB1BC1B5126F525E ON stock_movement (item_id)');
        $this->addSql('CREATE INDEX IDX_BB1BC1B5B56DCD74 ON stock_movement (licencie_id)');
        $this->addSql('CREATE INDEX IDX_BB1BC1B5B03A8386 ON stock_movement (created_by_id)');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E0A61F4EC001D1 ON team (season_id)');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant NUMERIC(8, 2) NOT NULL, mode VARCHAR(255) NOT NULL, reference VARCHAR(100) DEFAULT NULL, date_paiement DATE NOT NULL, licencie_id UUID NOT NULL, confirmed_by_id INT NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1B56DCD74 ON transaction (licencie_id)');
        $this->addSql('CREATE INDEX IDX_723705D16F45385D ON transaction (confirmed_by_id)');
        $this->addSql('CREATE INDEX IDX_723705D14EC001D1 ON transaction (season_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE dossier_club ADD CONSTRAINT FK_34D4F901B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (uuid) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE licencie ADD CONSTRAINT FK_3B75561212469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE licencie ADD CONSTRAINT FK_3B755612296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE licencie ADD CONSTRAINT FK_3B7556124EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_item ADD CONSTRAINT FK_6017DDA4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B5126F525E FOREIGN KEY (item_id) REFERENCES stock_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B5B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (uuid) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1B56DCD74 FOREIGN KEY (licencie_id) REFERENCES licencie (uuid) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D16F45385D FOREIGN KEY (confirmed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D14EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dossier_club DROP CONSTRAINT FK_34D4F901B56DCD74');
        $this->addSql('ALTER TABLE licencie DROP CONSTRAINT FK_3B75561212469DE2');
        $this->addSql('ALTER TABLE licencie DROP CONSTRAINT FK_3B755612296CD8AE');
        $this->addSql('ALTER TABLE licencie DROP CONSTRAINT FK_3B7556124EC001D1');
        $this->addSql('ALTER TABLE stock_item DROP CONSTRAINT FK_6017DDA4EC001D1');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B5126F525E');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B5B56DCD74');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B5B03A8386');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61F4EC001D1');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1B56DCD74');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D16F45385D');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D14EC001D1');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE dossier_club');
        $this->addSql('DROP TABLE licencie');
        $this->addSql('DROP TABLE season');
        $this->addSql('DROP TABLE stock_item');
        $this->addSql('DROP TABLE stock_movement');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
    }
}
