<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * EXPAND (1/3) — bascule du registre des clés au niveau du club.
 *
 * Le registre était cloisonné par saison : au 1er juillet, il repartait à zéro alors
 * que les clés étaient toujours dehors. La détention remonte donc au club, via une
 * nouvelle entité `detenteur` qui ne dépend d'aucune saison ; seul l'engagement
 * signé reste annuel, dans `attestation_cle`.
 *
 * Cette première étape n'ajoute que du vide : deux tables neuves et une colonne
 * nullable sur `cle_mouvement`. Rien n'est déplacé, rien n'est supprimé — la
 * reprise des données est dans Version20260810120100, la pose des contraintes dans
 * Version20260810120200.
 */
final class Version20260810120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'EXPAND : crée detenteur et attestation_cle, ajoute cle_mouvement.detenteur_id (nullable).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE detenteur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, num_licence VARCHAR(50) DEFAULT NULL, qualite VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE attestation_cle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, demande_envoyee_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, nb_cles INT DEFAULT NULL, remise_le DATE DEFAULT NULL, drive_path VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, detenteur_id INT NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2E81141D17F50A6 ON attestation_cle (uuid)');
        $this->addSql('CREATE INDEX IDX_2E81141742F89B9 ON attestation_cle (detenteur_id)');
        $this->addSql('CREATE INDEX IDX_2E811414EC001D1 ON attestation_cle (season_id)');
        $this->addSql('CREATE INDEX idx_attestation_cle_detenteur_season ON attestation_cle (detenteur_id, season_id)');
        $this->addSql('ALTER TABLE attestation_cle ADD CONSTRAINT FK_2E81141742F89B9 FOREIGN KEY (detenteur_id) REFERENCES detenteur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attestation_cle ADD CONSTRAINT FK_2E811414EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');

        // Nullable et sans FK à ce stade : la colonne se remplit à l'étape suivante.
        // PostgreSQL l'ajoute en métadonnée seule, sans réécrire la table.
        $this->addSql('ALTER TABLE cle_mouvement ADD detenteur_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_45D1DEB4742F89B9 ON cle_mouvement (detenteur_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX IDX_45D1DEB4742F89B9');
        $this->addSql('ALTER TABLE cle_mouvement DROP detenteur_id');

        $this->addSql('ALTER TABLE attestation_cle DROP CONSTRAINT FK_2E81141742F89B9');
        $this->addSql('ALTER TABLE attestation_cle DROP CONSTRAINT FK_2E811414EC001D1');
        $this->addSql('DROP TABLE attestation_cle');
        $this->addSql('DROP TABLE detenteur');
    }
}
