<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628162735 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 3 : fournisseurs, catalogue partagé (StockItem sans saison), taille mouvement, commandes';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, note TEXT DEFAULT NULL, season_id INT NOT NULL, fournisseur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D4EC001D1 ON commande (season_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D670C757F ON commande (fournisseur_id)');
        $this->addSql('CREATE TABLE commande_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taille VARCHAR(20) DEFAULT NULL, quantite INT NOT NULL, quantite_recue INT NOT NULL, prix_unitaire DOUBLE PRECISION DEFAULT NULL, commande_id INT NOT NULL, stock_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6E98044082EA2E54 ON commande_ligne (commande_id)');
        $this->addSql('CREATE INDEX IDX_6E980440BC942FD ON commande_ligne (stock_item_id)');
        $this->addSql('CREATE TABLE fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, contact VARCHAR(180) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande_ligne ADD CONSTRAINT FK_6E98044082EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande_ligne ADD CONSTRAINT FK_6E980440BC942FD FOREIGN KEY (stock_item_id) REFERENCES stock_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_item DROP CONSTRAINT fk_6017dda4ec001d1');
        $this->addSql('DROP INDEX idx_6017dda4ec001d1');
        $this->addSql('ALTER TABLE stock_item ADD fournisseur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stock_item DROP season_id');
        $this->addSql('ALTER TABLE stock_item ADD CONSTRAINT FK_6017DDA670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6017DDA670C757F ON stock_item (fournisseur_id)');
        $this->addSql('ALTER TABLE stock_movement ADD taille VARCHAR(20) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D4EC001D1');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D670C757F');
        $this->addSql('ALTER TABLE commande_ligne DROP CONSTRAINT FK_6E98044082EA2E54');
        $this->addSql('ALTER TABLE commande_ligne DROP CONSTRAINT FK_6E980440BC942FD');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commande_ligne');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('ALTER TABLE stock_item DROP CONSTRAINT FK_6017DDA670C757F');
        $this->addSql('DROP INDEX IDX_6017DDA670C757F');
        $this->addSql('ALTER TABLE stock_item ADD season_id INT NOT NULL');
        $this->addSql('ALTER TABLE stock_item DROP fournisseur_id');
        $this->addSql('ALTER TABLE stock_item ADD CONSTRAINT fk_6017dda4ec001d1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_6017dda4ec001d1 ON stock_item (season_id)');
        $this->addSql('ALTER TABLE stock_movement DROP taille');
    }
}
