<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Planning des matchs à domicile : table `match_domicile` et rattachement du club à la FFF.
 *
 * NON DESTRUCTIF. Une table créée, deux colonnes ajoutées à `club_settings` — table à ligne
 * unique déjà remplie, d'où `fff_sync_active` en NOT NULL **avec DEFAULT** (§13).
 *
 * ⚠️ Le SQL auto-généré proposait en plus de supprimer `cle_mouvement.season_id`,
 * `cle_mouvement.dirigeant_id`, les trois colonnes `dirigeant.attestation_cle_*` et
 * `season.iban/bic/titulaire_compte`. Ces colonnes sont **dé-mappées volontairement** et
 * portent des données réelles : elles ont été retirées de cette migration. Un `diff` futur
 * les reproposera — ne pas les laisser passer.
 *
 * `fff_sync_active` vaut `false` : la migration installe la synchronisation quotidienne,
 * elle ne l'allume pas. Elle s'allume après une synchronisation manuelle qui a montré ce
 * qu'elle ramène — d'autant que l'accès à l'API FFF depuis le serveur n'est pas garanti.
 */
final class Version20260829180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Planning des matchs à domicile : table match_domicile + rattachement FFF du club';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE match_domicile (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                season_id INT NOT NULL,
                date DATE NOT NULL,
                heure VARCHAR(5) DEFAULT NULL,
                categorie VARCHAR(60) NOT NULL,
                adversaire VARCHAR(100) DEFAULT NULL,
                note VARCHAR(255) DEFAULT NULL,
                source VARCHAR(10) NOT NULL,
                fff_ma_no INT DEFAULT NULL,
                fff_competition VARCHAR(120) DEFAULT NULL,
                fff_terrain VARCHAR(120) DEFAULT NULL,
                masque BOOLEAN DEFAULT false NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql('CREATE INDEX IDX_2B4A87344EC001D1 ON match_domicile (season_id)');
        $this->addSql('CREATE INDEX idx_match_domicile_season_date ON match_domicile (season_id, date)');

        // PostgreSQL considère deux NULL comme distincts : les matchs saisis à la main, tous
        // sans ma_no, cohabitent sans se gêner. La contrainte ne borne que le flux fédéral.
        $this->addSql('CREATE UNIQUE INDEX uniq_match_domicile_fff ON match_domicile (season_id, fff_ma_no)');

        // CASCADE : un planning n'a aucun sens hors de sa saison, et il se régénère.
        $this->addSql(<<<'SQL'
            ALTER TABLE match_domicile
                ADD CONSTRAINT FK_2B4A87344EC001D1 FOREIGN KEY (season_id)
                REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);

        $this->addSql('ALTER TABLE club_settings ADD fff_club_no INT DEFAULT NULL');
        $this->addSql('ALTER TABLE club_settings ADD fff_sync_active BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // DESTRUCTIF : les matchs saisis à la main sont perdus. Ceux venus de la FFF se
        // resynchronisent, les plateaux non — ils n'existent nulle part ailleurs.
        $this->addSql('ALTER TABLE match_domicile DROP CONSTRAINT FK_2B4A87344EC001D1');
        $this->addSql('DROP TABLE match_domicile');
        $this->addSql('ALTER TABLE club_settings DROP fff_club_no');
        $this->addSql('ALTER TABLE club_settings DROP fff_sync_active');
    }
}
