<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Documents signables pilotés en base.
 *
 * Jusqu'ici, chaque document que le club fait signer était codé en dur : une colonne
 * texte sur season, une paire de colonnes de signature sur l'entité signataire, un cas
 * d'enum, un service d'archivage. Ajouter une charte demandait un déploiement.
 *
 * Cette migration fait passer les deux règlements existants dans document_signable et
 * leurs signatures dans document_signature, sans rien perdre : les colonnes historiques
 * sont conservées et simplement dé-mappées des entités. Elles seront supprimées par une
 * migration « contract » distincte, une fois la bascule validée en production.
 */
final class Version20260807233000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée document_signable / document_signature et y bascule les règlements intérieurs existants.';
    }

    public function up(Schema $schema): void
    {
        // ── Schéma ────────────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE document_signable (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, season_id INT NOT NULL, code VARCHAR(60) NOT NULL, titre VARCHAR(150) NOT NULL, libelle VARCHAR(255) NOT NULL, contenu_html TEXT DEFAULT NULL, cible VARCHAR(20) NOT NULL, roles JSON NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, sort_order INT DEFAULT 0 NOT NULL, drive_segments JSON NOT NULL, file_prefix VARCHAR(30) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D9B879EF4EC001D1 ON document_signable (season_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_signable_season_code ON document_signable (season_id, code)');
        $this->addSql('ALTER TABLE document_signable ADD CONSTRAINT FK_D9B879EF4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE document_signable_dirigeant (document_id INT NOT NULL, dirigeant_uuid UUID NOT NULL, PRIMARY KEY (document_id, dirigeant_uuid))');
        $this->addSql('CREATE INDEX IDX_52FA179AC33F7837 ON document_signable_dirigeant (document_id)');
        $this->addSql('CREATE INDEX IDX_52FA179A1688CA9D ON document_signable_dirigeant (dirigeant_uuid)');
        $this->addSql('ALTER TABLE document_signable_dirigeant ADD CONSTRAINT FK_52FA179AC33F7837 FOREIGN KEY (document_id) REFERENCES document_signable (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_signable_dirigeant ADD CONSTRAINT FK_52FA179A1688CA9D FOREIGN KEY (dirigeant_uuid) REFERENCES dirigeant (uuid) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE document_signature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_id INT NOT NULL, dirigeant_uuid UUID DEFAULT NULL, licencie_uuid UUID DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, drive_path VARCHAR(500) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BCB029E0C33F7837 ON document_signature (document_id)');
        $this->addSql('CREATE INDEX IDX_BCB029E01688CA9D ON document_signature (dirigeant_uuid)');
        $this->addSql('CREATE INDEX IDX_BCB029E01694F1A2 ON document_signature (licencie_uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_signature_dirigeant ON document_signature (document_id, dirigeant_uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_signature_licencie ON document_signature (document_id, licencie_uuid)');
        $this->addSql('ALTER TABLE document_signature ADD CONSTRAINT FK_BCB029E0C33F7837 FOREIGN KEY (document_id) REFERENCES document_signable (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_signature ADD CONSTRAINT FK_BCB029E01688CA9D FOREIGN KEY (dirigeant_uuid) REFERENCES dirigeant (uuid) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_signature ADD CONSTRAINT FK_BCB029E01694F1A2 FOREIGN KEY (licencie_uuid) REFERENCES licencie (uuid) ON DELETE CASCADE NOT DEFERRABLE');

        // dossier_club.is_signed reste NOT NULL mais n'est plus écrite par Doctrine :
        // sans DEFAULT, toute création de dossier échouerait.
        $this->addSql('ALTER TABLE dossier_club ALTER COLUMN is_signed SET DEFAULT false');

        // ── Reprise des deux règlements existants, pour chaque saison ──────────────
        // Créés même sans texte rédigé, pour que l'admin les retrouve dans la liste.
        // driveSegments et filePrefix reprennent l'arborescence Drive historique :
        // rien ne bouge pour les documents déjà archivés.
        $this->addSql(<<<'SQL'
            INSERT INTO document_signable (season_id, code, titre, libelle, contenu_html, cible, roles, actif, sort_order, drive_segments, file_prefix)
            SELECT s.id,
                   'reglement_licencie',
                   'Règlement intérieur',
                   'le règlement intérieur du Foyer de Soudron',
                   s.reglement_text,
                   'licencie',
                   '[]'::json,
                   true,
                   10,
                   '["Règlements intérieurs signés"]'::json,
                   'RI'
            FROM season s
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO document_signable (season_id, code, titre, libelle, contenu_html, cible, roles, actif, sort_order, drive_segments, file_prefix)
            SELECT s.id,
                   'reglement_dirigeant',
                   'Règlement intérieur des dirigeants',
                   'le règlement intérieur des dirigeants du Foyer de Soudron',
                   s.reglement_dirigeant_text,
                   'dirigeant',
                   '[]'::json,
                   true,
                   10,
                   '["Règlements intérieurs signés", "Dirigeants"]'::json,
                   'RI_Dirigeant'
            FROM season s
        SQL);

        // ── Reprise des signatures déjà recueillies ────────────────────────────────
        // drive_path est repris tel quel : chemin local en attente d'upload ou ID Drive,
        // le rattrapage (app:drive-retry-upload) continue de fonctionner sans rien perdre.
        $this->addSql(<<<'SQL'
            INSERT INTO document_signature (document_id, licencie_uuid, signed_at, drive_path)
            SELECT doc.id,
                   l.uuid,
                   COALESCE(dc.signature_date, dc.form_completed_at, NOW()),
                   dc.signature_path
            FROM dossier_club dc
            JOIN licencie l ON l.uuid = dc.licencie_id
            JOIN document_signable doc ON doc.season_id = l.season_id AND doc.code = 'reglement_licencie'
            WHERE dc.is_signed = true
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO document_signature (document_id, dirigeant_uuid, signed_at, drive_path)
            SELECT doc.id,
                   d.uuid,
                   COALESCE(d.reglement_signed_at, d.form_completed_at, NOW()),
                   d.reglement_signe_path
            FROM dirigeant d
            JOIN document_signable doc ON doc.season_id = d.season_id AND doc.code = 'reglement_dirigeant'
            WHERE d.reglement_signe_path IS NOT NULL
        SQL);
    }

    /**
     * DESTRUCTIF : supprime les documents créés depuis l'admin et toutes les signatures
     * postérieures à la bascule. Les colonnes historiques n'ayant jamais été supprimées,
     * les signatures d'avant migration, elles, sont intactes.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE dossier_club ALTER COLUMN is_signed DROP DEFAULT');
        $this->addSql('DROP TABLE document_signature');
        $this->addSql('DROP TABLE document_signable_dirigeant');
        $this->addSql('DROP TABLE document_signable');
    }
}
