<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Sort le référentiel des tailles du code pour le poser en base, réglable depuis
 * /admin/club/tailles.

 * Jusqu'ici la liste vivait dans une constante PHP : ajouter une déclinaison du fournisseur
 * demandait un déploiement. Le club doit pouvoir le faire lui-même, comme il le fait déjà
 * pour les catégories FFF.
 *
 * NON DESTRUCTIF — une table neuve, peuplée du référentiel **exactement tel qu'il était en
 * dur** : mêmes libellés, donc les tailles déjà écrites dans `dossier_club`, `dirigeant`,
 * `stock_movement` et `dotation_besoin` continuent de correspondre ligne pour ligne. Aucune
 * colonne existante n'est touchée.
 *
 * `proposee_aux_licencies` reprend la distinction qui existait déjà dans le code : les
 * étiquetages fournisseur (centimètres, lettres enfant) ne sont pas proposés aux licenciés.
 */
final class Version20260815170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table taille et y verse le référentiel jusque-là codé en dur';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE taille (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(20) NOT NULL, type VARCHAR(20) NOT NULL, groupe VARCHAR(50) DEFAULT NULL, proposee_aux_licencies BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_taille_type_libelle ON taille (type, libelle)');

        $this->addSql(<<<'SQL'
            INSERT INTO taille (libelle, type, groupe, proposee_aux_licencies, position) VALUES
                   ('XS', 'vetement', 'Tailles adultes', true, 1),
                   ('S', 'vetement', 'Tailles adultes', true, 2),
                   ('M', 'vetement', 'Tailles adultes', true, 3),
                   ('L', 'vetement', 'Tailles adultes', true, 4),
                   ('XL', 'vetement', 'Tailles adultes', true, 5),
                   ('XXL', 'vetement', 'Tailles adultes', true, 6),
                   ('3XL', 'vetement', 'Tailles adultes', true, 7),
                   ('4XL', 'vetement', 'Tailles adultes', true, 8),
                   ('6 ans', 'vetement', 'Tailles enfants', true, 9),
                   ('8 ans', 'vetement', 'Tailles enfants', true, 10),
                   ('10 ans', 'vetement', 'Tailles enfants', true, 11),
                   ('12 ans', 'vetement', 'Tailles enfants', true, 12),
                   ('14 ans', 'vetement', 'Tailles enfants', true, 13),
                   ('16 ans', 'vetement', 'Tailles enfants', true, 14),
                   ('104', 'vetement', 'Tailles enfants (fournisseur)', false, 15),
                   ('116', 'vetement', 'Tailles enfants (fournisseur)', false, 16),
                   ('128', 'vetement', 'Tailles enfants (fournisseur)', false, 17),
                   ('140', 'vetement', 'Tailles enfants (fournisseur)', false, 18),
                   ('152', 'vetement', 'Tailles enfants (fournisseur)', false, 19),
                   ('164', 'vetement', 'Tailles enfants (fournisseur)', false, 20),
                   ('176', 'vetement', 'Tailles enfants (fournisseur)', false, 21),
                   ('XS enfant', 'vetement', 'Tailles enfants (fournisseur)', false, 22),
                   ('S enfant', 'vetement', 'Tailles enfants (fournisseur)', false, 23),
                   ('M enfant', 'vetement', 'Tailles enfants (fournisseur)', false, 24),
                   ('L enfant', 'vetement', 'Tailles enfants (fournisseur)', false, 25),
                   ('XL enfant', 'vetement', 'Tailles enfants (fournisseur)', false, 26),
                   ('24', 'pointure', NULL, true, 27),
                   ('25', 'pointure', NULL, true, 28),
                   ('26', 'pointure', NULL, true, 29),
                   ('27', 'pointure', NULL, true, 30),
                   ('28', 'pointure', NULL, true, 31),
                   ('29', 'pointure', NULL, true, 32),
                   ('30', 'pointure', NULL, true, 33),
                   ('31', 'pointure', NULL, true, 34),
                   ('32', 'pointure', NULL, true, 35),
                   ('33', 'pointure', NULL, true, 36),
                   ('34', 'pointure', NULL, true, 37),
                   ('35', 'pointure', NULL, true, 38),
                   ('36', 'pointure', NULL, true, 39),
                   ('37', 'pointure', NULL, true, 40),
                   ('38', 'pointure', NULL, true, 41),
                   ('39', 'pointure', NULL, true, 42),
                   ('40', 'pointure', NULL, true, 43),
                   ('41', 'pointure', NULL, true, 44),
                   ('42', 'pointure', NULL, true, 45),
                   ('43', 'pointure', NULL, true, 46),
                   ('44', 'pointure', NULL, true, 47),
                   ('45', 'pointure', NULL, true, 48),
                   ('46', 'pointure', NULL, true, 49),
                   ('47', 'pointure', NULL, true, 50),
                   ('48', 'pointure', NULL, true, 51),
                   ('49', 'pointure', NULL, true, 52),
                   ('50', 'pointure', NULL, true, 53)
            SQL);
    }

    public function down(Schema $schema): void
    {
        // PERTE DE DONNÉES : les tailles ajoutées par le club depuis /admin/club/tailles.
        // Le code retomberait sur la liste figée, sans elles.
        $this->addSql('DROP TABLE taille');
    }
}
