<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Référentiel des fonctions du club et son rattachement aux dirigeants.
 *
 * Ce que la personne fait — « Coordinateur général », « Entraîneur » — par opposition à son
 * rôle, qui dit ce que l'application lui doit. La mairie demande la fonction des détenteurs
 * de clés, et le rôle ne savait pas y répondre : trois personnes partagent
 * `responsable_foot` sans qu'aucune ne soit *le* responsable de la section.
 *
 * Purement additive : deux tables neuves, aucune colonne existante touchée. Le diff
 * automatique proposait en plus de supprimer `cle_mouvement.dirigeant_id`,
 * `cle_mouvement.season_id`, les trois colonnes `dirigeant.attestation_cle_*` et les
 * coordonnées bancaires de `season` — colonnes volontairement laissées en base, dé-mappées,
 * le temps de valider leurs bascules respectives. Les rejouer ici perdrait ces données.
 */
final class Version20260912111418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Référentiel des fonctions du club et rattachement aux dirigeants';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE fonction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(120) NOT NULL, porte_equipe BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fonction_libelle ON fonction (libelle)');

        $this->addSql('CREATE TABLE dirigeant_fonction (dirigeant_uuid UUID NOT NULL, fonction_id INT NOT NULL, PRIMARY KEY (dirigeant_uuid, fonction_id))');
        $this->addSql('CREATE INDEX IDX_8053B7521688CA9D ON dirigeant_fonction (dirigeant_uuid)');
        $this->addSql('CREATE INDEX IDX_8053B75257889920 ON dirigeant_fonction (fonction_id)');
        $this->addSql('ALTER TABLE dirigeant_fonction ADD CONSTRAINT FK_8053B7521688CA9D FOREIGN KEY (dirigeant_uuid) REFERENCES dirigeant (uuid) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dirigeant_fonction ADD CONSTRAINT FK_8053B75257889920 FOREIGN KEY (fonction_id) REFERENCES fonction (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE dirigeant_fonction DROP CONSTRAINT FK_8053B7521688CA9D');
        $this->addSql('ALTER TABLE dirigeant_fonction DROP CONSTRAINT FK_8053B75257889920');
        $this->addSql('DROP TABLE dirigeant_fonction');
        $this->addSql('DROP TABLE fonction');
    }
}
