<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260624195223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX idx_dirigeant_role_id RENAME TO IDX_BEC71E71D60322AC');
        $this->addSql('ALTER TABLE dirigeant_role ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dirigeant_role ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_dirigeant_role_label RENAME TO UNIQ_909E1051EA750E8');
        $this->addSql('ALTER TABLE stock_item ADD kind VARCHAR(20) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX idx_bec71e71d60322ac RENAME TO idx_dirigeant_role_id');
        $this->addSql('ALTER TABLE dirigeant_role ALTER id SET DEFAULT nextval(\'dirigeant_role_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dirigeant_role ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_909e1051ea750e8 RENAME TO uniq_dirigeant_role_label');
        $this->addSql('ALTER TABLE stock_item DROP kind');
    }
}
