# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    club.email_expediteur: '%env(default:club_email_expediteur_defaut:CLUB_EMAIL_EXPEDITEUR)%'
    club.nom_expediteur: '%env(default:club_nom_expediteur_defaut:CLUB_NOM_EXPEDITEUR)%'
    club.email_reponse: '%env(default:club_email_reponse_defaut:CLUB_EMAIL_REPONSE)%'
    club_email_expediteur_defaut: 'contact@foyerdesoudron.fr'
    club_nom_expediteur_defaut: 'Foyer de Soudron'
    club_email_reponse_defaut: 'soudron.fr@marne.lgef.fr'

    app.pdf_dir: '%kernel.project_dir%/var/pdfs'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Twig\AppExtension:
        arguments:
            $nomClub: '%club.nom_expediteur%'

    App\Service\Mail\ClubMailer:
        arguments:
            $emailExpediteur: '%club.email_expediteur%'
            $nomExpediteur: '%club.nom_expediteur%'
            $emailReponse: '%club.email_reponse%'

    App\Service\Mail\DiagMailerService:
        arguments:
            $emailExpediteur: '%club.email_expediteur%'
            $nomExpediteur: '%club.nom_expediteur%'
            $emailReponse: '%club.email_reponse%'

    _instanceof:
        App\Service\Import\Layout\ImportLayoutInterface:
            tags: ['app.import_layout']
